### ISSUE TITLE
Problemas con la práctica 2.

### ISSUE THREAD

**Issue by FranciscoNaveros** [mabarrbai/TusPachangas#1]
Tienes que demostrarme que tu repositorio pasao satisfactoriamente la integración continua. De lo contrario, la práctica estará suspensa.

**Comment by mabarrbai** [comment]
Ah vale, es que lo tengo hecho en los ejercicios porque he usado mi proyecto para realizar todos los ejercicios. Voy a añadirlo al readme.md entonces.
Gracias

**Comment by mabarrbai** [comment]
Actualizado el Readme.md con las imágenes que demuestran que mi repositorio pasa las pruebas de integración continua con Travis.
